### ISSUE TITLE
Split `beesdoo_product` into ??? - analyse

### ISSUE THREAD

**Issue by carmenbianca** [beescoop/Obeesdoo#353]
https://github.com/coopiteasy/vertical-cooperative/issues/204 suggests to split into `product_label` and `sale_suggested_price`, but #264 implies that there are a lot more target modules.

**Comment by robinkeunen** [comment]
Also before managing `consignes`, this PR should be fixed: https://github.com/beescoop/Obeesdoo/issues/369

**Comment by robinkeunen** [comment]
also see https://github.com/beescoop/Obeesdoo/blob/12.0/beesdoo_product/readme/DESCRIPTION.rst

**Comment by robinkeunen** [comment]
@carmenbianca @victor-champonnois Here is a first analysis of the work needed for beesdoo_product. I do not have the time to create the tasks before leaving to 🇩🇿

## For all features :
- check again if no equivalent in OCA
- check proper name
- always develop and merge in this repository. Move to other repositories when suggested once stable (make a new task to keep track of it)

## Feature by feature

**Adds the label bio/ethique/provenance.**
Task : migrate `beesdoo_product`'s labels to grap's `product_label`
https://github.com/grap/grap-odoo-business/tree/12.0/product_label

**Adds hazard and FDS labels.**
Task: split `beesdoo_product` into `product_hazard` (oca/product-attribute)

**Adds a main seller.**
Task: split `beesdoo_product` into `product_main_supplier`

**Calculates total price with VAT and deposit price.**
Task: split `beesdoo_product` into `sale_product_deposit`

**Contains some facilitation for label printing.**
Task: split `beesdoo_product` into `product_label_print_request`
or is it deprecated with new work on labels ? => check w/ analyst

**Adds a 'Comments' field for use on labels.**
Task: split `beesdoo_product` into `product_note` (oca/product-attribute)

**Adds deadline for sale and consumption.**
Task: split `beesdoo_product` into `product_expiration` (deadline_for_consumption)
Task: split `beesdoo_product` into `product_sale_limit_date` (deadline_for_sale)
=> check if used or whether it can be removed
=> question the field name (`expiration_date` and `sale_limit_date` ?)

**Adds an 'Ingredients' field.**
Task: split `beesdoo_product` into `product_ingredients` (oca/product-attribute)
=> rename field `ingredients` to `composition` ?

**Adds scale labels, sale units, and categories.**
Used for connection to BIZERBA scales only at the bees coop.
move `beesdoo_product` to `bees_bizerba` (coopiteasy/cie-custom)

**Generates barcodes.**
Task: split `beesdoo_product` into `beesdoo_barcode`
add note to ROADMAP.rst : migrate to https://github.com/OCA/stock-logistics-barcode

**Suggested Price**
Task: split `beesdoo_product` into `sale_suggested_price`

- Adds a 'Suggested Price' field on products, and a 'Product Margin' field on Partners (Vendors) and Product Categories.
  The first margin is used if set, otherwise the second margin (which has a default value) is used.
- The reference price on which this margin is applied (supplier price or sale price)
  can be selected in the general settings.
- Also, sale and supplier taxes that are of type 'percentage' and that are marked as 'included in price'
  are taken into account when computing the suggested price.
- Round suggested price to 5 cents

**Adds "Edit Price" submenu on Point Of Sale, Purchase and Sale modules.**
Task: split `beesdoo_product` into `sale_edit_price_wizard`

**Comment by carmenbianca** [comment]
In addition:

https://github.com/beescoop/Obeesdoo/pull/320

This PR should become its own module.

edit: or should be roped into `sale_suggested_price`.

**Comment by victor-champonnois** [comment]
Note : beesdoo_product contains several data files with noudpate=True.
- https://github.com/beescoop/Obeesdoo/blob/12.0/beesdoo_product/data/product_sequence.xml and https://github.com/beescoop/Obeesdoo/blob/12.0/beesdoo_product/data/barcode_rule.xml that should go to the `beesdoo_barcode`
- https://github.com/beescoop/Obeesdoo/blob/12.0/beesdoo_product/data/product_hazard.xml that should go to the `product_hazard` module
- https://github.com/beescoop/Obeesdoo/blob/12.0/beesdoo_product/data/product_label.xml that should go to `product_label` (or `product_hazard` I don't know)

My point is that, since we will have to install some of these modules (we cannot rename a source module to several target modules), the install will override the changes made by the client.

After discussing with @huguesdk, he had the idea of, instead of installing the module, just setting its state as "installed" in the ir_module_module table (after renaming the xml_ids).
