### ISSUE TITLE
Merge `beesdoo_product_usability` into `product_main_supplierinfo`

### ISSUE THREAD

**Issue by carmenbianca** [beescoop/Obeesdoo#360]
Also backport `product_main_supplierinfo` to 12.0.

**Comment by victor-champonnois** [comment]
@robinkeunen Oups, my PR merge beesdoo_product_usability into obeesdoo's product_main_supplier. I misundertood.

**Comment by victor-champonnois** [comment]
I have the impression that [product_main_supplierinfo](https://github.com/OCA/product-attribute/blob/14.0/product_main_supplierinfo/models/product_product.py) is doing more or less the same thing as Obeesdoo's `product_main_supplier`.

- Should we merge `product_main_supplier` into `product_main_supplierinfo` ?
- If not, if we merge `beesdoo_product_usability` into `product_main_supplierinfo`, would not be able to use it because we would have to install `product_main_supplierinfo`, while already having  `product_main_supplier`.
