### ISSUE TITLE
Migrate beesdoo_product's labels to grap's product_label

### ISSUE THREAD

**Issue by robinkeunen** [beescoop/Obeesdoo#400]
Adds the label bio/ethique/provenance.
https://github.com/grap/grap-odoo-business/tree/12.0/product_label

**Comment by victor-champonnois** [comment]
- Should we add the `type` field to the grap's product_label model ? It is a non-intrusive change, although it would be useless since label_ids is no categorization of label in the grap's module. 
- prerecorded data are in data in `obeesdoo` and in demo in `grap`, should we follow grap and put them in demo ? Do we need the data at all ?
    - If we need them : need translate the name in the data in english
- The grap product label is structured as one many2many field from product to product_label, while in obeesdoo, there are several many2one field. Grap's structure seems simpler and more generic, so we follow it ?
An more broadly, has there been discussions with le Grap about this ?
@robinkeunen

**Comment by robinkeunen** [comment]
> * Should we add the `type` field to the grap's product_label model ? It is a non-intrusive change, although it would be useless since label_ids is no categorization of label in the grap's module.
> * prerecorded data are in data in `obeesdoo` and in demo in `grap`, should we follow grap and put them in demo ? Do we need the data at all ?
>   
>   * If we need them : need translate the name in the data in english
> * The grap product label is structured as one many2many field from product to product_label, while in obeesdoo, there are several many2one field. Grap's structure seems simpler and more generic, so we follow it ?

I think the GRAP design is better but I'm afraid to touch at this right now: we spent a LOT of time on product label (I mean _étiquettes_) and just released the development a few weeks ago. Refactoring the product labels would affect the templates...

Let's leave it for December, what do you think ?

>   And more broadly, has there been discussions with le Grap about this ?

I don't think we had a discussion about this with the GRAP.

**Comment by victor-champonnois** [comment]
@robinkeunen OK, I am happy to leave it like this for now

**Comment by robinkeunen** [comment]
@victor-champonnois I don't think we will have time for a refactor here. I think we should just rename the module to `beesdoo_label` when it's empty.

**Comment by victor-champonnois** [comment]
OK

**Comment by victor-champonnois** [comment]
renamed to beesdoo_product_label to be more precise
